[package]
name = "ldap"
version = "0.0.1"
authors = [ "Dean Davis <dean4devil@chaingamers.com>" ]

description = "FFI Bindings for libldap"
repository = "https://github.com/dean4devil/rust-ldap"
readme = "README.md"

keywords = ["ldap", "libldap"]

license = "MIT"

[dependencies]
