[package]
authors = ["Ivan Nejgebauer <inejge@gmail.com>", "Gregor Reitzenstein <dean4devil@paranoidlabs.org>"]
description = "Pure-Rust LDAPv3 Client"
documentation = "https://docs.rs/ldap3"
keywords = ["ldap", "client", "tokio", "async"]
license = "MIT/Apache-2.0"
name = "ldap3"
readme = "README.md"
repository = "https://github.com/inejge/ldap3"
version = "0.4.3"

[dependencies]
byteorder = "1.0.0"
bytes = "0.4.1"
futures = "0.1"
lazy_static = "0.2.4"
log = "0.3.6"
native-tls = "0.1.1"
nom = "2.0"
tokio-core = "0.1"
tokio-io = "0.1.1"
tokio-proto = "0.1"
tokio-service = "0.1"
url = "1.4.0"

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.1.4"
tokio-uds-proto = "0.1"

[dependencies.lber]
path = "lber"
version = "0.1.4"

[dependencies.tokio-tls]
features = ["tokio-proto"]
version = "0.1.2"

[dependencies.clippy]
version = "0.0.129"
optional = true

[features]
default = []

[dev-dependencies]
env_logger = "0.4.2"
maplit = "0.1.4"

[workspace]
members = [".", "lber"]
