[package]
authors = ["Ivan Nejgebauer <inejge@gmail.com>"]
description = "Pure-Rust LDAPv3 Client"
documentation = "https://docs.rs/ldap3"
keywords = ["ldap", "client", "tokio", "async"]
license = "MIT/Apache-2.0"
name = "ldap3"
readme = "README.md"
repository = "https://github.com/inejge/ldap3"
version = "0.7.0-alpha.1"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "io-util", "rt-core", "stream", "sync", "time", "uds"] }
tokio-util = { version = "0.3", features = ["codec"] }
bytes = "0.5"
nom = "2"
url = "2"
futures = "0.3.4"
percent-encoding = "2.1.0"
futures-util = "0.3.4"
log = "0.4.8"
lazy_static = "1.4.0"
thiserror = "1.0.15"

[dependencies.lber]
path = "lber"
version = "0.1.7"

[workspace]
members = [".", "lber"]
