[package]
name = "ldap"
version = "0.1.0"
authors = ["Dean4Devil <dean4devil@paranoidlabs.org>"]

description = "Pure Rust LDAP Libraries"
repository = "https://github.com/dean4devil/rust-ldap"
readme = "README.md"

keywords = ["ldap", "libldap"]

license = "MIT/Apache-2.0"

[dependencies]
ldap_protocol = { path = "protocol/", version = "^0" }
ldap_client = { path = "client/", version = "^0" }
