[package]
authors = ["Gregor Reitzenstein <dean4devil@paranoidlabs.org>"]
description = "Pure Rust LDAP Implementation (Not abandonware anymore!)"
documentation = "https://docs.rs/ldap"
keywords = ["ldap", "libldap"]
license = "MIT/Apache-2.0"
name = "ldap"
readme = "README.md"
repository = "https://github.com/dequbed/rust-ldap"
version = "0.3.0"

[dependencies]
byteorder = "1.0.0"
bytes = "0.4.1"
futures = "0.1"
log = "0.3.6"
native-tls = "0.1.1"
nom = "2.0"
tokio-core = "0.1"
tokio-io = "0.1.1"
tokio-proto = "0.1"
tokio-service = "0.1"
url = "1.4.0"

[dependencies.asnom]
path = "asnom"

[dependencies.tokio-tls]
features = ["tokio-proto"]
version = "0.1.2"

[dev-dependencies]
env_logger = "0.4.2"
